name: Update Repository (Development)
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  js-test:
    name: Run CDK Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Deps
        run: pnpm install

      - name: Run Tests
        run: echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY && pnpm run test:ci >> $GITHUB_STEP_SUMMARY && echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GH-Actions-Deploy-Development-Constructs

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.5

      - name: Initialize Terraform
        working-directory: ./iac
        run: terraform init --backend-config=development.config
        
      - name: Run Terraform Plan
        working-directory: ./iac
        run: terraform plan --var-file=development.tfvars -out=tfplan.bin

      - name: Show Terraform Plan
        working-directory: ./iac
        run: echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY && terraform show -no-color tfplan.bin >> $GITHUB_STEP_SUMMARY && echo "\`\`\`"  >> $GITHUB_STEP_SUMMARY

      - name: Store JSON Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: iac/tfplan.bin
          retention-days: 1

  terraform-apply:
    name: Terraform Apply
    environment: development
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GH-Actions-Deploy-development-ConstructRepo


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.5

      - name: Initialize Terraform
        working-directory: ./iac
        run: terraform init --backend-config=development.config

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v5
        with:
          name: terraform-plan
          path: ./iac

      - name: Run Terraform Apply
        working-directory: ./iac
        run: terraform apply tfplan.bin

  publish-beta-cdk-pkg:
    name: Publish Beta CDK Package
    environment: development
    runs-on: ubuntu-latest
    needs: [terraform-apply]
    steps:
      - name: checkout-code
        uses: actions/checkout@v6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GH-Actions-Deploy-development-ConstructRepo

      - name: log into codeArtifact
        run: aws codeartifact login --tool npm --repository registry-development-repo --domain registry-development --domain-owner 903936256209 --region eu-west-2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: "pnpm --frozen-lockfile"

      - name: Publish
        run: "pnpm publish --tag alpha"

